### ISSUE TITLE
DOI - price feed still enabled with Bitcoin

### ISSUE THREAD

**Issue by NiKrause** [Doichain/electrum-doi#1]
When enabling the price feed via coingecko, its seems Electrum ist still requesting the price for BTC instead of DOI.
<img width="455" alt="Bildschirmfoto 2021-07-22 um 18 12 07" src="https://user-images.githubusercontent.com/283618/126644527-a744a9bd-c8de-498f-8eb7-abb72114b04c.png">

Please find the coin gecko url in the sources and replace it with a DOI request! Unfortunately only Coinpaprika lists DOI at the moment, so maybe it is possible to replace the Coingecko feed with Coinpaprika
https://coinpaprika.com/coin/doi-doicoin/

**Comment by stallingerl** [comment]
Exchanged the coingecko api with the coinpaprika api for current and historic doi prices.

As Doichain doesn't have any current exchange rates on coinpaprika, currently a fallback to March 18th 2021 is used as an exchange rate.
