### ISSUE TITLE
Fehlermeldung "disconnecting due to RPCError"

### ISSUE THREAD

**Issue by davidreband** [Doichain/electrum-doi#7]
W/i | interface.[big-parrot-60.doi.works:50002] | disconnecting due to RPCError(-32600, 'response too large (over 10,000,000 bytes')

**Comment by stallingerl** [comment]
INFO | network | disconnecting from pink-deer-69.doi.works:50002:s. too many connected servers already in bucket 2a01:4f8:c0c::/48

session Problem? 

Löscht man in .electrum-doi den Inhalt der Ordner certs und cache und löscht die Blockchain_headers file verschwindet das Problem und taucht nach ca. 15 Min. wieder auf.

**Comment by stallingerl** [comment]
checkpoints.json hat gefehlt. Solved by [commit](https://github.com/Doichain/electrum-doi/commit/f4bc3b2c565a28baacaab2eb70b52ca42b5ac80c)
